### ISSUE TITLE
In Android it does not redirect to app after login

### ISSUE THREAD

**Issue by datteroandrea** [choutkamartin/next-auth-capacitor#2]
In Android it does not redirect to app after login

**Comment by choutkamartin** [comment]
Hi, as I stated somewhere else, it stopped working, give me few days to fix it, thank you

**Comment by choutkamartin** [comment]
Fixed in this commit https://github.com/choutkamartin/next-auth-capacitor/commit/108d78b3a1516e297d7eb0ede040e24fd432418b

It should automatically close the in app browser and return you to your app. The app itself will then reload the page to load session.

PS: Logout won't probably work, because it makes a fetch call via the official Next Auth function and therefore it doesn't include cookies when doing cross-site request. You would need to write own `logout` function. I will try to make it work in the upcoming days, but I'm running low on time right now.

You pretty much need to work around Next Auth limitation, as it simply doesn't support cross site requests eg. not including cookies. Which is a pain in the ass.
