### ISSUE TITLE
How did you create a subdomain in vercel?

### ISSUE THREAD

**Issue by datteroandrea** [choutkamartin/next-auth-capacitor#3]
Hello, thanks a lot for fixing the previous issues, how did you create a subdomain in vercel? did you pay to have one?

**Comment by choutkamartin** [comment]
Which subdomain?

**Comment by datteroandrea** [comment]
mob.next-auth-capacitor.vercel.app is bring used for mobile devices, how did you set it up? thanks for the efforts!

**Comment by choutkamartin** [comment]
It's actually not a true subdomain. It's a hostname of the application itself, therefore you could put there (I think) even domains you don't own as `google.com`. The hostname is subdomain of the domain our API is hosted on because we need to share cookies easily. Therefore, when the application makes requests to our API (Next Auth especially), the origin of the request is seen as a subdomain, therefore not only you can easily configure CORS, but you can also share cookies from the Next application that is running on Vercel with your Android application.

Also bear in mind, that when doing this from Android, the origin of the application is seen as `https://mob...`, which is exactly what we need. However, iOS as a system blocks the usage of `https://` for applications, therefore Capacitor can't use this schema, and instead the origin is seen as `capacitor://mob...` which would make cookies not work. Therefore for iOS you need to use a different strategy. But maybe the schema isn't blocked in newer versions of iOS, but I highly doubt that.

You can also not use this entire repository as an example and instead use `server.url` inside Capacitor config. Server URL can be set to the URL of your Next.js application running somewhere on the internet (for example Vercel). Then, the application would not use any of the build static assets and instead it would need to make requests to your Next.js app to do everything. Think of it as something as an `iframe`. The positive side is that you will not have problems with cookies, as the application is then just container over a web application. The negative side is that the user has to be connected to the internet the entire time and Apple prohibits applications that load everything over the internet. I mean not strictly prohibit, but they don't recommend it and they don't like it, so it may get your application not allowed on the app store.

**Comment by datteroandrea** [comment]
Perfect, awesome explanation!

**Comment by yongloon** [comment]
If i change the hostname to `main.next-auth-capacitor.vercel.app` and the header value to `https://main.next-auth-capacitor.vercel.app`

its not working, what is the issue?
