### ISSUE TITLE
localhost / development

### ISSUE THREAD

**Issue by GGAlanSmithee** [choutkamartin/next-auth-capacitor#4]
Hi @choutkamartin 

Thanks for this example repo!

I am trying to retrofit this into an existing stack, with some complexity to it. I just wanted to check with you if this is expected to work locally (http://localhost:3000) before digging too deep.

Many thanks!

**Comment by choutkamartin** [comment]
Hi, no, it's not expected to run locally without doing any additional changes to the code itself. Currently on localhost, you would get a CORS error, because the distant app running on Vercel doesn't allow requests from localhost.

That's why `apiHost` is set to `next-auth-capacitor.vercel.app` instead of `localhost:3000` as I try to simulate with this repository a production use. In production use the application user uses would make requests to you server, not to a localhost. 

```ts
const appConfig = {
  apiHost: "https://next-auth-capacitor.vercel.app", // Set the domain where your API is hosted on
};

export default appConfig;
```

You could theoretically just set apiHost to `localhost:3000`, and if you set correctly GitHub OAuth, it should be working. On mobile, you could set the `capacitor.config` to the below, which should allow your phone to use your current running instance of Next as server (assuming you connected your phone to your PC).
```
server: {
	url: 'http://192.168.x.xx:3000',
	cleartext: true
}
```

Bear in mind, that there are some caveats such as https://forum.ionicframework.com/t/https-for-the-app-server-protocol-instead-of-capacitor-on-ios/200116/2, that make it very hard for you to make a working app for both Android and iOS. 

I made this example repo as at least something people can have as a starting point, because I never found a truly working example repo with a functioning `apk`, that doesn't use `server.url` set to the website itself. 

If you have any other questions, feel free to ask. Also, you can read this issue https://github.com/choutkamartin/next-auth-capacitor/issues/3, where I provide additional context.

--- 
And thanks for the question, added this as a notice to the README

**Comment by GGAlanSmithee** [comment]
thanks for the taking the time to answer @choutkamartin 

We have made more or less the changes you suggested already, and I think we are more or less there, but it's not trivial to debug, but will continue tomorrow, and report back if we get it working or not.

Thanks!

**Comment by choutkamartin** [comment]
No problem, feel free to ask me anytime

Next Auth and Capacitor is pain in the ass to make work together 😆

**Comment by BjoernRave** [comment]
@GGAlanSmithee did you succeed to make it work on localhost? Can you share your steps?

**Comment by GGAlanSmithee** [comment]
@BjoernRave sorry no, and unfortunately, we had a lot of cookies-related issues which forced us (for the time being anyhow) to abandon next-auth. We had some hope that this would be easier / resolved with Capcitor 5, but so far no luck.

**Comment by akanz** [comment]
currently have issues with next-auth with capacitor. has anyone being able to solve this issue?
